markdown: rdiscount
pygments: true

navigation:
- title: Home
  url: ./
- title: Projects
  url: projects.html
- title: Design
  url: design.html
- title: Food
  url: downloads.html
- title: Contact
  url: contact.html

javascript_compressor: closure

javascripts:
  application:

stylesheets:
  screen:
    - _site/css/primary.css
